version: '3.8'

services:
  rag-tutor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10002:8080"
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}