version: '3.8'

services:
  oilgas_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:80"
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}